# Generated by Django 6.0.7 on 2026-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, help_text='e.g., Apple, Samsung, Asus', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict, help_text="Store characteristics as JSON. (e.g., {'RAM': '16GB', 'Storage': '512GB'})"),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sold', 'brand'], name='shop_produc_is_sold_3538a2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sold', '-created_at'], name='shop_produc_is_sold_ea3fb4_idx'),
        ),
    ]
