# Generated by Django 6.0.7 on 2026-08-09 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(help_text='Required Kyrgyz Passport ID (e.g. ID1234567)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Passport must start with ID or AN followed by 7 digits (e.g., ID1234567).', regex='^(ID|AN)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Kyrgyz format: +996XXXXXXXXX', regex='^\\+996\\d{9}$')]),
        ),
    ]
